# Set the base image to use the official Node.js 14.x image
FROM node:16-alpine

# Create a new directory in the container to hold the app
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY package*.json ./

# Install the app's dependencies
RUN npm install

# Copy the rest of the app into the container
COPY . .

# Start the app using Node.js
CMD ["npm", "run", "dev"]